#include <qt_key.hpp>
#include <unordered_map>

namespace anton_engine {
    Key key_from_qt_key(Qt::Key const kb) {
        static std::unordered_map<Qt::Key, Key> const keyboard_buttons{
            {Qt::Key_Escape, Key::escape},
            {Qt::Key_Tab, Key::tab},
            {Qt::Key_Backspace, Key::backspace},
            {Qt::Key_Return, Key::enter}, // TODO differentiate between enter and return (maybe)
            {Qt::Key_Enter, Key::enter},
            {Qt::Key_Insert, Key::insert},
            {Qt::Key_Delete, Key::delete_key},
            //{Qt::Key_Pause, },
            {Qt::Key_Home, Key::home},
            {Qt::Key_End, Key::end},
            {Qt::Key_Left, Key::left},
            {Qt::Key_Up, Key::up},
            {Qt::Key_Right, Key::right},
            {Qt::Key_Down, Key::down},
            {Qt::Key_PageUp, Key::page_up},
            {Qt::Key_PageDown, Key::page_down},
            {Qt::Key_Shift, Key::left_shift}, // TODO which shift
            //{Qt::Key_Control, },
            // {Qt::Key_Meta,}, Windows/Control key
            {Qt::Key_Alt, Key::left_alt},   // TODO which alt
            {Qt::Key_AltGr, Key::left_alt}, // TODO which alt
            {Qt::Key_CapsLock, Key::caps_lock},
            {Qt::Key_NumLock, Key::num_lock},
            //{Qt::Key_ScrollLock,},
            {Qt::Key_F1, Key::f1},
            {Qt::Key_F2, Key::f2},
            {Qt::Key_F3, Key::f3},
            {Qt::Key_F4, Key::f4},
            {Qt::Key_F5, Key::f5},
            {Qt::Key_F6, Key::f6},
            {Qt::Key_F7, Key::f7},
            {Qt::Key_F8, Key::f8},
            {Qt::Key_F9, Key::f9},
            {Qt::Key_F10, Key::f10},
            {Qt::Key_F11, Key::f11},
            {Qt::Key_F12, Key::f12},
            {Qt::Key_Space, Key::spacebar},
            {Qt::Key_Any, Key::any_key},
            //{Qt::Key_Exclam,},
            //{Qt::Key_QuoteDbl,},
            //{Qt::Key_Dollar,},
            //{Qt::Key_Percent,},
            //{Qt::Key_Ampersand,},
            //{Qt::Key_Apostrophe,},
            //{Qt::Key_ParenLeft,},
            //{Qt::Key_ParenRight,},
            //{Qt::Key_Asterisk,},
            //{Qt::Key_Plus,},
            //{Qt::Key_Comma,},
            //{Qt::Key_Minus,},
            //{Qt::Key_Period,},
            //{Qt::Key_Slash,},
            {Qt::Key_0, Key::zero},
            {Qt::Key_1, Key::one},
            {Qt::Key_2, Key::two},
            {Qt::Key_3, Key::three},
            {Qt::Key_4, Key::four},
            {Qt::Key_5, Key::five},
            {Qt::Key_6, Key::six},
            {Qt::Key_7, Key::seven},
            {Qt::Key_8, Key::eight},
            {Qt::Key_9, Key::nine},
            //{Qt::Key_Colon,},
            //{Qt::Key_Semicolon,},
            //{Qt::Key_Less,},
            //{Qt::Key_Equal,},
            //{Qt::Key_Greater,},
            //{Qt::Key_Question,},
            //{Qt::Key_At,},
            {Qt::Key_A, Key::a},
            {Qt::Key_B, Key::b},
            {Qt::Key_C, Key::c},
            {Qt::Key_D, Key::d},
            {Qt::Key_E, Key::e},
            {Qt::Key_F, Key::f},
            {Qt::Key_G, Key::g},
            {Qt::Key_H, Key::h},
            {Qt::Key_I, Key::i},
            {Qt::Key_J, Key::j},
            {Qt::Key_K, Key::k},
            {Qt::Key_L, Key::l},
            {Qt::Key_M, Key::m},
            {Qt::Key_N, Key::n},
            {Qt::Key_O, Key::o},
            {Qt::Key_P, Key::p},
            {Qt::Key_Q, Key::q},
            {Qt::Key_R, Key::r},
            {Qt::Key_S, Key::s},
            {Qt::Key_T, Key::t},
            {Qt::Key_U, Key::u},
            {Qt::Key_V, Key::v},
            {Qt::Key_W, Key::w},
            {Qt::Key_X, Key::x},
            {Qt::Key_Y, Key::y},
            {Qt::Key_Z, Key::z},
            //{Qt::Key_BracketLeft,},
            //{Qt::Key_Backslash,},
            //{Qt::Key_BracketRight,},
            //{Qt::Key_Underscore,},
            //{Qt::Key_QuoteLeft,},
            //{Qt::Key_BraceLeft,},
            //{Qt::Key_Bar,},
            //{Qt::Key_BraceRight,},
            //{Qt::Key_AsciiTilde,}
        };

        return keyboard_buttons.at(kb);
    }
    Key key_from_qt_mouse_button(Qt::MouseButton const mb) {
        static std::unordered_map<Qt::MouseButton, Key> const mouse_buttons{
            {Qt::MouseButton::LeftButton, Key::left_mouse_button},     {Qt::MouseButton::RightButton, Key::right_mouse_button},
            {Qt::MouseButton::MiddleButton, Key::middle_mouse_button}, {Qt::MouseButton::XButton1, Key::thumb_mouse_button_1},
            {Qt::MouseButton::XButton2, Key::thumb_mouse_button_2},    {Qt::MouseButton::ExtraButton3, Key::mouse_button_6},
            {Qt::MouseButton::ExtraButton4, Key::mouse_button_7},      {Qt::MouseButton::ExtraButton5, Key::mouse_button_8},
        };

        return mouse_buttons.at(mb);
    }
} // namespace anton_engine
