#ifndef GAMEENGINE_CORE_CORE_TYPE_DEFINITIONS_HPP_INCLUDE
#define GAMEENGINE_CORE_CORE_TYPE_DEFINITIONS_HPP_INCLUDE

using uint32 = unsigned int;
using uint64 = unsigned long long;

#endif // !GAMEENGINE_CORE_CORE_TYPE_DEFINITIONS_HPP_INCLUDE