#include <engine/key.hpp>

#include <unordered_map>

namespace anton_engine {
    bool is_mouse_axis(Key const k) {
        return k == Key::mouse_x | k == Key::mouse_y | k == Key::mouse_scroll;
    }

    bool is_gamepad_axis(Key const k) {
        return k == Key::gamepad_right_stick_x_axis | k == Key::gamepad_right_stick_y_axis | k == Key::gamepad_left_stick_x_axis |
               k == Key::gamepad_left_stick_y_axis | k == Key::gamepad_left_trigger | k == Key::gamepad_right_trigger;
    }

    bool is_gamepad_stick(Key const k) {
        return k == Key::gamepad_right_stick_x_axis | k == Key::gamepad_right_stick_y_axis | k == Key::gamepad_left_stick_x_axis |
               k == Key::gamepad_left_stick_y_axis;
    }

    atl::String_View key_to_string(Key key) {
        // clang-format off
        static std::unordered_map<Key, atl::String_View> key_string({
            {Key::none, "none"},
            {Key::any_key, "any_key"},
            {Key::mouse_x, "mouse_x"},
            {Key::mouse_y, "mouse_y"},
            {Key::mouse_scroll, "mouse_scroll"},
            {Key::mouse_horiz_scroll, "mouse_horiz_scroll"},
            {Key::left_mouse_button, "left_mouse_button"},
            {Key::right_mouse_button, "right_mouse_button"},
            {Key::middle_mouse_button, "middle_mouse_button"},
            {Key::thumb_mouse_button_1, "thumb_mouse_button_1"},
            {Key::thumb_mouse_button_2, "thumb_mouse_button_2"},
            {Key::mouse_button_6, "mouse_button_6"},
            {Key::mouse_button_7, "mouse_button_7"},
            {Key::mouse_button_8, "mouse_button_8"},
            {Key::escape, "escape"},
            {Key::enter, "enter"},
            {Key::tab, "tab"},
            {Key::caps_lock, "caps_lock"},
            {Key::spacebar, "spacebar"},
            {Key::backspace, "backspace"},
            {Key::left_alt, "left_alt"},
            {Key::right_alt, "right_alt"},
            {Key::left_shift, "left_shift"},
            {Key::right_shift, "right_shift"},
            {Key::left_control, "left_control"},
            {Key::right_control, "right_control"},
            {Key::numpad_0, "numpad_0"},
            {Key::numpad_1, "numpad_1"},
            {Key::numpad_2, "numpad_2"},
            {Key::numpad_3, "numpad_3"},
            {Key::numpad_4, "numpad_4"},
            {Key::numpad_5, "numpad_5"},
            {Key::numpad_6, "numpad_6"},
            {Key::numpad_7, "numpad_7"},
            {Key::numpad_8, "numpad_8"},
            {Key::numpad_9, "numpad_9"},
            {Key::numpad_add, "numpad_add"},
            {Key::numpad_subtract, "numpad_subtract"},
            {Key::numpad_divide, "numpad_divide"},
            {Key::numpad_multiply, "numpad_multiply"},
            {Key::numpad_decimal, "numpad_decimal"},
            {Key::numpad_enter, "numpad_enter"},
            {Key::numlock, "numlock"},
            {Key::left, "left"},
            {Key::right, "right"},
            {Key::up, "up"},
            {Key::down, "down"},
            {Key::insert, "insert"},
            {Key::home, "home"},
            {Key::page_up, "page_up"},
            {Key::page_down, "page_down"},
            {Key::end, "end"},
            {Key::del, "del"},
            {Key::zero, "zero"},
            {Key::one, "one"},
            {Key::two, "two"},
            {Key::three, "three"},
            {Key::four, "four"},
            {Key::five, "five"},
            {Key::six, "six"},
            {Key::seven, "seven"},
            {Key::eight, "eight"},
            {Key::nine, "nine"},
            {Key::a, "a"},
            {Key::b, "b"},
            {Key::c, "c"},
            {Key::d, "d"},
            {Key::e, "e"},
            {Key::f, "f"},
            {Key::g, "g"},
            {Key::h, "h"},
            {Key::i, "i"},
            {Key::j, "j"},
            {Key::k, "k"},
            {Key::l, "l"},
            {Key::m, "m"},
            {Key::n, "n"},
            {Key::o, "o"},
            {Key::p, "p"},
            {Key::q, "q"},
            {Key::r, "r"},
            {Key::s, "s"},
            {Key::t, "t"},
            {Key::u, "u"},
            {Key::v, "v"},
            {Key::w, "w"},
            {Key::x, "x"},
            {Key::y, "y"},
            {Key::z, "z"},
            {Key::slash, "slash"},
            {Key::comma, "comma"},
            {Key::dot, "dot"},
            {Key::semicolon, "semicolon"},
            {Key::left_bracket, "left_bracket"},
            {Key::right_bracket, "right_bracket"},
            {Key::minus, "minus"},
            {Key::equals, "equals"},
            {Key::apostrophe, "apostrophe"},
            {Key::tick, "tick"},
            {Key::backward_slash, "backward_slash"},
            {Key::f1, "f1"},
            {Key::f2, "f2"},
            {Key::f3, "f3"},
            {Key::f4, "f4"},
            {Key::f5, "f5"},
            {Key::f6, "f6"},
            {Key::f7, "f7"},
            {Key::f8, "f8"},
            {Key::f9, "f9"},
            {Key::f10, "f10"},
            {Key::f11, "f11"},
            {Key::f12, "f12"},
            {Key::pause, "pause"},
            {Key::gamepad_left_stick_x_axis, "gamepad_left_stick_x_axis"},
            {Key::gamepad_left_stick_y_axis, "gamepad_left_stick_y_axis"},
            {Key::gamepad_right_stick_x_axis, "gamepad_right_stick_x_axis"},
            {Key::gamepad_right_stick_y_axis, "gamepad_right_stick_y_axis"},
            {Key::gamepad_left_trigger, "gamepad_left_trigger"},
            {Key::gamepad_right_trigger, "gamepad_right_trigger"},
            {Key::gamepad_button_0, "gamepad_button_0"},
            {Key::gamepad_button_1, "gamepad_button_1"},
            {Key::gamepad_button_2, "gamepad_button_2"},
            {Key::gamepad_button_3, "gamepad_button_3"},
            {Key::gamepad_button_4, "gamepad_button_4"},
            {Key::gamepad_button_5, "gamepad_button_5"},
            {Key::gamepad_button_6, "gamepad_button_6"},
            {Key::gamepad_button_7, "gamepad_button_7"},
            {Key::gamepad_button_8, "gamepad_button_8"},
            {Key::gamepad_button_9, "gamepad_button_9"},
            {Key::gamepad_button_10, "gamepad_button_10"},
            {Key::gamepad_button_11, "gamepad_button_11"},
            {Key::gamepad_button_12, "gamepad_button_12"},
            {Key::gamepad_button_13, "gamepad_button_13"},
            {Key::gamepad_button_14, "gamepad_button_14"},
            {Key::gamepad_button_15, "gamepad_button_15"},
            {Key::gamepad_button_16, "gamepad_button_16"},
            {Key::gamepad_button_17, "gamepad_button_17"},
            {Key::gamepad_button_18, "gamepad_button_18"},
            {Key::gamepad_button_19, "gamepad_button_19"}
        });
        // clang-format on
        return key_string.at(key);
    }

    Key key_from_string(atl::String_View const str) {
        // clang-format off
        static std::unordered_map<u64, Key> string_key({
            {atl::hash("none"), Key::none},
            {atl::hash("any_key"), Key::any_key},
            {atl::hash("mouse_x"), Key::mouse_x},
            {atl::hash("mouse_y"), Key::mouse_y},
            {atl::hash("mouse_scroll"), Key::mouse_scroll},
            {atl::hash("mouse_horiz_scroll"), Key::mouse_horiz_scroll},
            {atl::hash("left_mouse_button"), Key::left_mouse_button},
            {atl::hash("right_mouse_button"), Key::right_mouse_button},
            {atl::hash("middle_mouse_button"), Key::middle_mouse_button},
            {atl::hash("thumb_mouse_button_1"), Key::thumb_mouse_button_1},
            {atl::hash("thumb_mouse_button_2"), Key::thumb_mouse_button_2},
            {atl::hash("mouse_button_6"), Key::mouse_button_6},
            {atl::hash("mouse_button_7"), Key::mouse_button_7},
            {atl::hash("mouse_button_8"), Key::mouse_button_8},
            {atl::hash("escape"), Key::escape},
            {atl::hash("enter"), Key::enter},
            {atl::hash("tab"), Key::tab},
            {atl::hash("caps_lock"), Key::caps_lock},
            {atl::hash("spacebar"), Key::spacebar},
            {atl::hash("backspace"), Key::backspace},
            {atl::hash("left_alt"), Key::left_alt},
            {atl::hash("right_alt"), Key::right_alt},
            {atl::hash("left_shift"), Key::left_shift},
            {atl::hash("right_shift"), Key::right_shift},
            {atl::hash("left_control"), Key::left_control},
            {atl::hash("right_control"), Key::right_control},
            {atl::hash("numpad_0"), Key::numpad_0},
            {atl::hash("numpad_1"), Key::numpad_1},
            {atl::hash("numpad_2"), Key::numpad_2},
            {atl::hash("numpad_3"), Key::numpad_3},
            {atl::hash("numpad_4"), Key::numpad_4},
            {atl::hash("numpad_5"), Key::numpad_5},
            {atl::hash("numpad_6"), Key::numpad_6},
            {atl::hash("numpad_7"), Key::numpad_7},
            {atl::hash("numpad_8"), Key::numpad_8},
            {atl::hash("numpad_9"), Key::numpad_9},
            {atl::hash("numpad_add"), Key::numpad_add},
            {atl::hash("numpad_subtract"), Key::numpad_subtract},
            {atl::hash("numpad_divide"), Key::numpad_divide},
            {atl::hash("numpad_multiply"), Key::numpad_multiply},
            {atl::hash("numpad_decimal"), Key::numpad_decimal},
            {atl::hash("numpad_enter"), Key::numpad_enter},
            {atl::hash("numlock"), Key::numlock},
            {atl::hash("left"), Key::left},
            {atl::hash("right"), Key::right},
            {atl::hash("up"), Key::up},
            {atl::hash("down"), Key::down},
            {atl::hash("insert"), Key::insert},
            {atl::hash("home"), Key::home},
            {atl::hash("page_up"), Key::page_up},
            {atl::hash("page_down"), Key::page_down},
            {atl::hash("end"), Key::end},
            {atl::hash("del"), Key::del},
            {atl::hash("zero"), Key::zero},
            {atl::hash("one"), Key::one},
            {atl::hash("two"), Key::two},
            {atl::hash("three"), Key::three},
            {atl::hash("four"), Key::four},
            {atl::hash("five"), Key::five},
            {atl::hash("six"), Key::six},
            {atl::hash("seven"), Key::seven},
            {atl::hash("eight"), Key::eight},
            {atl::hash("nine"), Key::nine},
            {atl::hash("a"), Key::a},
            {atl::hash("b"), Key::b},
            {atl::hash("c"), Key::c},
            {atl::hash("d"), Key::d},
            {atl::hash("e"), Key::e},
            {atl::hash("f"), Key::f},
            {atl::hash("g"), Key::g},
            {atl::hash("h"), Key::h},
            {atl::hash("i"), Key::i},
            {atl::hash("j"), Key::j},
            {atl::hash("k"), Key::k},
            {atl::hash("l"), Key::l},
            {atl::hash("m"), Key::m},
            {atl::hash("n"), Key::n},
            {atl::hash("o"), Key::o},
            {atl::hash("p"), Key::p},
            {atl::hash("q"), Key::q},
            {atl::hash("r"), Key::r},
            {atl::hash("s"), Key::s},
            {atl::hash("t"), Key::t},
            {atl::hash("u"), Key::u},
            {atl::hash("v"), Key::v},
            {atl::hash("w"), Key::w},
            {atl::hash("x"), Key::x},
            {atl::hash("y"), Key::y},
            {atl::hash("z"), Key::z},
            {atl::hash("slash"), Key::slash},
            {atl::hash("comma"), Key::comma},
            {atl::hash("dot"), Key::dot},
            {atl::hash("semicolon"), Key::semicolon},
            {atl::hash("left_bracket"), Key::left_bracket},
            {atl::hash("right_bracket"), Key::right_bracket},
            {atl::hash("minus"), Key::minus},
            {atl::hash("equals"), Key::equals},
            {atl::hash("apostrophe"), Key::apostrophe},
            {atl::hash("tick"), Key::tick},
            {atl::hash("backward_slash"), Key::backward_slash},
            {atl::hash("f1"), Key::f1},
            {atl::hash("f2"), Key::f2},
            {atl::hash("f3"), Key::f3},
            {atl::hash("f4"), Key::f4},
            {atl::hash("f5"), Key::f5},
            {atl::hash("f6"), Key::f6},
            {atl::hash("f7"), Key::f7},
            {atl::hash("f8"), Key::f8},
            {atl::hash("f9"), Key::f9},
            {atl::hash("f10"), Key::f10},
            {atl::hash("f11"), Key::f11},
            {atl::hash("f12"), Key::f12},
            {atl::hash("pause"), Key::pause},
            {atl::hash("gamepad_left_stick_x_axis"), Key::gamepad_left_stick_x_axis},
            {atl::hash("gamepad_left_stick_y_axis"), Key::gamepad_left_stick_y_axis},
            {atl::hash("gamepad_right_stick_x_axis"), Key::gamepad_right_stick_x_axis},
            {atl::hash("gamepad_right_stick_y_axis"), Key::gamepad_right_stick_y_axis},
            {atl::hash("gamepad_left_trigger"), Key::gamepad_left_trigger},
            {atl::hash("gamepad_right_trigger"), Key::gamepad_right_trigger},
            {atl::hash("gamepad_button_0"), Key::gamepad_button_0},
            {atl::hash("gamepad_button_1"), Key::gamepad_button_1},
            {atl::hash("gamepad_button_2"), Key::gamepad_button_2},
            {atl::hash("gamepad_button_3"), Key::gamepad_button_3},
            {atl::hash("gamepad_button_4"), Key::gamepad_button_4},
            {atl::hash("gamepad_button_5"), Key::gamepad_button_5},
            {atl::hash("gamepad_button_6"), Key::gamepad_button_6},
            {atl::hash("gamepad_button_7"), Key::gamepad_button_7},
            {atl::hash("gamepad_button_8"), Key::gamepad_button_8},
            {atl::hash("gamepad_button_9"), Key::gamepad_button_9},
            {atl::hash("gamepad_button_10"), Key::gamepad_button_10},
            {atl::hash("gamepad_button_11"), Key::gamepad_button_11},
            {atl::hash("gamepad_button_12"), Key::gamepad_button_12},
            {atl::hash("gamepad_button_13"), Key::gamepad_button_13},
            {atl::hash("gamepad_button_14"), Key::gamepad_button_14},
            {atl::hash("gamepad_button_15"), Key::gamepad_button_15},
            {atl::hash("gamepad_button_16"), Key::gamepad_button_16},
            {atl::hash("gamepad_button_17"), Key::gamepad_button_17},
            {atl::hash("gamepad_button_18"), Key::gamepad_button_18},
            {atl::hash("gamepad_button_19"), Key::gamepad_button_19}
        });
        // clang-format on
        u64 const h = atl::hash(str);
        return string_key.at(h);
    }
} // namespace anton_engine
