#ifndef GAMEENGINE_CORE_INPUT_COMPONENT_HPP_INCLUDE
#define GAMEENGINE_CORE_INPUT_COMPONENT_HPP_INCLUDE

#include "../Core.hpp"

class Input_Component {};

#endif // !GAMEENGINE_CORE_INPUT_COMPONENT_HPP_INCLUDE