#ifndef BUILD_CONFIG_HPP_INCLUDE
#define BUILD_CONFIG_HPP_INCLUDE

#ifdef NDEBUG
#    define GE_DEBUG 0
#else
#    define GE_DEBUG 1
#endif

#ifndef GE_WITH_EDITOR
#    define GE_WITH_EDITOR 1
#endif

#ifndef GE_BUILD_SHIPPING_DEBUG
#    define GE_BUIlD_SHIPPING_DEBUG 0
#endif

#ifndef GE_BUILD_SHIPPING_RELEASE
#    define GE_BUIlD_SHIPPING_RELEASE 0
#endif

#ifndef GE_BUILD_SHIPPING
#    define GE_BUILD_SHIPPING GE_BUILD_SHIPPING_DEBUG || GE_BUILD_SHIPPING_RELEASE
#endif

#define SERIALIZE_ON_QUIT 0
#define DESERIALIZE 0

#endif // !BUILD_CONFIG_HPP_INCLUDE
