#ifndef BUILD_CONFIG_HPP_INCLUDE
#define BUILD_CONFIG_HPP_INCLUDE

#ifdef NDEBUG
#    define ANTON_DEBUG 0
#else
#    define ANTON_DEBUG 1
#endif

#ifndef ANTON_WITH_EDITOR
#    define ANTON_WITH_EDITOR 0
#endif

#ifndef GE_BUILD_SHIPPING_DEBUG
#    define GE_BUILD_SHIPPING_DEBUG 0
#endif

#ifndef GE_BUILD_SHIPPING_RELEASE
#    define GE_BUILD_SHIPPING_RELEASE 0
#endif

#ifndef GE_BUILD_SHIPPING
#    define GE_BUILD_SHIPPING GE_BUILD_SHIPPING_DEBUG || GE_BUILD_SHIPPING_RELEASE
#endif

// anton_stl library

#ifndef ANTON_STRING_VIEW_VERIFY_ENCODING
#    define ANTON_STRING_VIEW_VERIFY_ENCODING 1
#endif

#ifndef ANTON_STRING_VERIFY_ENCODING
#    define ANTON_STRING_VERIFY_ENCODING 1
#endif

// Unicode library

#ifndef ANTON_UNICODE_VALIDATE_ENCODING
#    define ANTON_UNICODE_VALIDATE_ENCODING 1
#endif

#define SERIALIZE_ON_QUIT 0
#define DESERIALIZE 0

#endif // !BUILD_CONFIG_HPP_INCLUDE
