#ifndef GAMEENGINE_CORE_CORE_MACRO_DEFINITIONS_HPP_INCLUDE
#define GAMEENGINE_CORE_CORE_MACRO_DEFINITIONS_HPP_INCLUDE

// #define GE_NAMESPACE_NAME GameEngine

// #define GE_BEGIN_NAMESPACE namespace GE_NAMESPACE_NAME {
// #define GE_END_NAMESPACE }

#endif // !GAMEENGINE_CORE_CORE_MACRO_DEFINITIONS_HPP_INCLUDE